from constants import HIST_QUANTILES, CON_MULTIPLIER, \
    BYR_HIST_MODEL, DELAY_MODELS, CON_MODELS, MSG_MODELS, DISCRIM_MODEL, \
    POLICY_SLR, POLICY_BYR, FIRST_ARRIVAL_MODEL, INTERARRIVAL_MODEL, \
    INTERVAL_CT_TURN, INTERVAL_CT_ARRIVAL

# size of model output
NUM_OUT = {
    FIRST_ARRIVAL_MODEL: INTERVAL_CT_ARRIVAL,
    INTERARRIVAL_MODEL: INTERVAL_CT_ARRIVAL + 1,
    BYR_HIST_MODEL: HIST_QUANTILES,
    POLICY_BYR: CON_MULTIPLIER + 1,
    POLICY_SLR: CON_MULTIPLIER + 2
}
for m in DELAY_MODELS:
    NUM_OUT[m] = INTERVAL_CT_TURN + 1
for m in CON_MODELS[:-1]:
    NUM_OUT[m] = CON_MULTIPLIER + 1
for m in [CON_MODELS[-1], DISCRIM_MODEL] + MSG_MODELS:
    NUM_OUT[m] = 1
