"""
Combines the categorical features generated by meta.py and slr.py into
a single dataframe for each chunk
"""
import argparse
from compress_pickle import dump, load
import pandas as pd
from constants import FEATS_DIR


def get_input_names(num, slr):
    name_list = list()
    for i in range(1, 8):
        if slr:
            name_list.append('{}{}_slr_feat_{}.gz'.format(FEATS_DIR, num, i))
        else:
            name_list.append('{}m{}_cat_feats_{}.gz'.format(FEATS_DIR, num, i))
    return name_list


def output_path(num, slr):
    if slr:
        return '{}{}_slr_feat.gz'.format(FEATS_DIR, num)
    else:
        return '{}{}_cat_feat.gz'.format(FEATS_DIR, num)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--num', action='store', type=int, required=True)
    parser.add_argument('--slr', action='store_true')
    args = parser.parse_args()
    input_list = get_input_names(args.num, args.slr)
    dfs = [load(input_file) for input_file in input_list]
    df = pd.concat(dfs, axis=1, sort=True)
    dump(df, output_path(args.num, args.slr))
