mkdir data/datasets/$1/consts/train
mkdir data/datasets/$1/consts/test
mkdir data/datasets/$1/consts/toy
mkdir data/datasets/$1/listing_chunks/toy
mkdir data/datasets/$1/listing_chunks/train
mkdir data/datasets/$1/listing_chunks/test
mkdir data/datasets/$1/listings/toy
mkdir data/datasets/$1/listings/test
mkdir data/datasets/$1/listings/train
mkdir data/datasets/$1/time/train
mkdir data/datasets/$1/time/test
mkdir data/datasets/$1/time/toy
